"""Added Transfer and TransactionLog models

Revision ID: 856d85c13977
Revises: da513e8e9132
Create Date: 2024-09-29 01:51:04.717969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856d85c13977'
down_revision = 'da513e8e9132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'transfer', ['transfer_id'], ['id'])

    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('transfer_id')

    # ### end Alembic commands ###
